# Site specific settings
title: "DC207"
name: "Website name"
keywords: "Maine, Hackers, DC207"
baseurl: "/darcli"
url: "http://www.dc207.org"
description: "Home of DC207"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
#disqus: test
#twitter: 
#facebook: 
#github: 
#google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
